// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/applications/index.tsx";
import * as $4 from "./routes/cloud/_middleware.tsx";
import * as $5 from "./routes/cloud/azure/auth/acquireToken.ts";
import * as $6 from "./routes/cloud/azure/auth/redirect.ts";
import * as $7 from "./routes/cloud/azure/auth/signin.ts";
import * as $8 from "./routes/cloud/azure/auth/signout.ts";
import * as $9 from "./routes/cloud/index.tsx";
import * as $10 from "./routes/data/index.tsx";
import * as $11 from "./routes/devices/[name].tsx";
import * as $12 from "./routes/devices/index.tsx";
import * as $13 from "./routes/index.tsx";
import * as $14 from "./routes/test-redirect.ts";
import * as $15 from "./routes/test.tsx";
import * as $$0 from "./islands/atoms/InteractiveMenuIcon.tsx";
import * as $$1 from "./islands/atoms/InteractiveSlideToggle.tsx";
import * as $$2 from "./islands/common/ProfileMenu.tsx";
import * as $$3 from "./islands/molecules/InteractiveResponsiveSet.tsx";
import * as $$4 from "./islands/organisms/CloudConnectForms.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/applications/index.tsx": $3,
    "./routes/cloud/_middleware.tsx": $4,
    "./routes/cloud/azure/auth/acquireToken.ts": $5,
    "./routes/cloud/azure/auth/redirect.ts": $6,
    "./routes/cloud/azure/auth/signin.ts": $7,
    "./routes/cloud/azure/auth/signout.ts": $8,
    "./routes/cloud/index.tsx": $9,
    "./routes/data/index.tsx": $10,
    "./routes/devices/[name].tsx": $11,
    "./routes/devices/index.tsx": $12,
    "./routes/index.tsx": $13,
    "./routes/test-redirect.ts": $14,
    "./routes/test.tsx": $15,
  },
  islands: {
    "./islands/atoms/InteractiveMenuIcon.tsx": $$0,
    "./islands/atoms/InteractiveSlideToggle.tsx": $$1,
    "./islands/common/ProfileMenu.tsx": $$2,
    "./islands/molecules/InteractiveResponsiveSet.tsx": $$3,
    "./islands/organisms/CloudConnectForms.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
