// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/applications/index.tsx";
import * as $3 from "./routes/cloud/index.tsx";
import * as $4 from "./routes/devices/[name].tsx";
import * as $5 from "./routes/devices/index.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/atoms/InteractiveSlideToggle.tsx";
import * as $$1 from "./islands/common/ProfileMenu.tsx";
import * as $$2 from "./islands/molecules/InteractiveResponsiveSet.tsx";
import * as $$3 from "./islands/organisms/CloudConnectForms.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/applications/index.tsx": $2,
    "./routes/cloud/index.tsx": $3,
    "./routes/devices/[name].tsx": $4,
    "./routes/devices/index.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/atoms/InteractiveSlideToggle.tsx": $$0,
    "./islands/common/ProfileMenu.tsx": $$1,
    "./islands/molecules/InteractiveResponsiveSet.tsx": $$2,
    "./islands/organisms/CloudConnectForms.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
