// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_data_middleware from "./routes/api/data/_middleware.ts";
import * as $api_data_clouds_auth_token from "./routes/api/data/clouds/auth-token.ts";
import * as $api_data_warm_explorer from "./routes/api/data/warm/explorer.ts";
import * as $api_eac_clouds_index from "./routes/api/eac/clouds/index.ts";
import * as $api_eac_clouds_iot_infrastructure from "./routes/api/eac/clouds/iot-infrastructure.ts";
import * as $api_eac_clouds_resource_groups from "./routes/api/eac/clouds/resource-groups.ts";
import * as $api_eac_connections from "./routes/api/eac/connections.ts";
import * as $api_eac_data_develop from "./routes/api/eac/data/develop.ts";
import * as $api_eac_data_explore from "./routes/api/eac/data/explore.ts";
import * as $api_eac_data_flow from "./routes/api/eac/data/flow.ts";
import * as $api_eac_github_user from "./routes/api/eac/github/user.ts";
import * as $api_eac_index from "./routes/api/eac/index.ts";
import * as $api_eac_iot_dashboards from "./routes/api/eac/iot/dashboards.ts";
import * as $api_eac_iot_data_apis_jwt from "./routes/api/eac/iot/data-apis-jwt.ts";
import * as $api_eac_iot_data_apis from "./routes/api/eac/iot/data-apis.ts";
import * as $api_eac_iot_devices_ensure from "./routes/api/eac/iot/devices/ensure.ts";
import * as $api_eac_stati from "./routes/api/eac/stati.ts";
import * as $api_eac_users from "./routes/api/eac/users.ts";
import * as $commit_commitId_status from "./routes/commit/[commitId]/status.tsx";
import * as $develop_index from "./routes/develop/index.tsx";
import * as $enterprises_entLookup_index from "./routes/enterprises/[[entLookup]]/index.tsx";
import * as $enterprises_clouds_cloudLookup_index from "./routes/enterprises/clouds/[[cloudLookup]]/index.tsx";
import * as $enterprises_devops_actions_doaLookup_index from "./routes/enterprises/devops-actions/[[doaLookup]]/index.tsx";
import * as $enterprises_handlers_handlerLookup_index from "./routes/enterprises/handlers/[[handlerLookup]]/index.tsx";
import * as $enterprises_iot_iotLookup_dashboards_dashboardLookup_index from "./routes/enterprises/iot/[[iotLookup]]/dashboards/[[dashboardLookup]]/index.tsx";
import * as $enterprises_iot_iotLookup_devices_deviceLookup_index from "./routes/enterprises/iot/[[iotLookup]]/devices/[[deviceLookup]]/index.tsx";
import * as $enterprises_iot_iotLookup_index from "./routes/enterprises/iot/[[iotLookup]]/index.tsx";
import * as $enterprises_iot_iotLookup_settings from "./routes/enterprises/iot/[[iotLookup]]/settings.tsx";
import * as $enterprises_secrets_secretLookup_index from "./routes/enterprises/secrets/[[secretLookup]]/index.tsx";
import * as $enterprises_source_connections_srcConnLookup_index from "./routes/enterprises/source-connections/[[srcConnLookup]]/index.tsx";
import * as $enterprises_sources_srcLookup_artifacts_artifactLookup_index from "./routes/enterprises/sources/[[srcLookup]]/artifacts/[[artifactLookup]]/index.tsx";
import * as $enterprises_sources_srcLookup_index from "./routes/enterprises/sources/[[srcLookup]]/index.tsx";
import * as $getting_started_applications_index from "./routes/getting-started/applications/index.tsx";
import * as $getting_started_cloud_middleware from "./routes/getting-started/cloud/_middleware.tsx";
import * as $getting_started_cloud_index from "./routes/getting-started/cloud/index.tsx";
import * as $getting_started_data_index from "./routes/getting-started/data/index.tsx";
import * as $getting_started_devices_index from "./routes/getting-started/devices/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $teams_index from "./routes/teams/index.tsx";
import * as $atoms_InteractiveMenuIcon from "./islands/atoms/InteractiveMenuIcon.tsx";
import * as $atoms_InteractiveSlideToggle from "./islands/atoms/InteractiveSlideToggle.tsx";
import * as $atoms_Redirect from "./islands/atoms/Redirect.tsx";
import * as $atoms_Theme from "./islands/atoms/Theme.tsx";
import * as $common_ProfileMenu from "./islands/common/ProfileMenu.tsx";
import * as $molecules_CopyInput from "./islands/molecules/CopyInput.tsx";
import * as $molecules_DeleteAction from "./islands/molecules/DeleteAction.tsx";
import * as $molecules_EaCManageIoTFormIsland from "./islands/molecules/EaCManageIoTFormIsland.tsx";
import * as $molecules_EaCManageSecretFormIsland from "./islands/molecules/EaCManageSecretFormIsland.tsx";
import * as $molecules_EaCManageSourceFormIsland from "./islands/molecules/EaCManageSourceFormIsland.tsx";
import * as $molecules_EntepriseManagementItem from "./islands/molecules/EntepriseManagementItem.tsx";
import * as $molecules_GitHubAccessAction from "./islands/molecules/GitHubAccessAction.tsx";
import * as $molecules_InteractiveResponsiveSet from "./islands/molecules/InteractiveResponsiveSet.tsx";
import * as $molecules_SideBar from "./islands/molecules/SideBar.tsx";
import * as $organisms_cloud_iot_hot_flow_input from "./islands/organisms/cloud/iot/hot-flow-input.tsx";
import * as $organisms_cloud_iot_res_group_iot_settings from "./islands/organisms/cloud/iot/res-group-iot-settings.tsx";
import * as $organisms_data_api_develop_form from "./islands/organisms/data/api-develop-form.tsx";
import * as $organisms_data_dashboard_display from "./islands/organisms/data/dashboard-display.tsx";
import * as $organisms_data_explore_form from "./islands/organisms/data/explore-form.tsx";
import * as $organisms_iot_device_data_flowing from "./islands/organisms/iot/device-data-flowing.tsx";
import * as $organisms_iot_devices_dashboard_controls from "./islands/organisms/iot/devices-dashboard-controls.tsx";
import * as $organisms_iot_hub_device_connection from "./islands/organisms/iot/hub-device-connection.tsx";
import * as $organisms_iot_hub_key_connection from "./islands/organisms/iot/hub-key-connection.tsx";
import * as $organisms_iot_hub_key_simulator from "./islands/organisms/iot/hub-key-simulator.tsx";
import * as $organisms_team_invite_team_member from "./islands/organisms/team/invite-team-member.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/data/_middleware.ts": $api_data_middleware,
    "./routes/api/data/clouds/auth-token.ts": $api_data_clouds_auth_token,
    "./routes/api/data/warm/explorer.ts": $api_data_warm_explorer,
    "./routes/api/eac/clouds/index.ts": $api_eac_clouds_index,
    "./routes/api/eac/clouds/iot-infrastructure.ts":
      $api_eac_clouds_iot_infrastructure,
    "./routes/api/eac/clouds/resource-groups.ts":
      $api_eac_clouds_resource_groups,
    "./routes/api/eac/connections.ts": $api_eac_connections,
    "./routes/api/eac/data/develop.ts": $api_eac_data_develop,
    "./routes/api/eac/data/explore.ts": $api_eac_data_explore,
    "./routes/api/eac/data/flow.ts": $api_eac_data_flow,
    "./routes/api/eac/github/user.ts": $api_eac_github_user,
    "./routes/api/eac/index.ts": $api_eac_index,
    "./routes/api/eac/iot/dashboards.ts": $api_eac_iot_dashboards,
    "./routes/api/eac/iot/data-apis-jwt.ts": $api_eac_iot_data_apis_jwt,
    "./routes/api/eac/iot/data-apis.ts": $api_eac_iot_data_apis,
    "./routes/api/eac/iot/devices/ensure.ts": $api_eac_iot_devices_ensure,
    "./routes/api/eac/stati.ts": $api_eac_stati,
    "./routes/api/eac/users.ts": $api_eac_users,
    "./routes/commit/[commitId]/status.tsx": $commit_commitId_status,
    "./routes/develop/index.tsx": $develop_index,
    "./routes/enterprises/[[entLookup]]/index.tsx":
      $enterprises_entLookup_index,
    "./routes/enterprises/clouds/[[cloudLookup]]/index.tsx":
      $enterprises_clouds_cloudLookup_index,
    "./routes/enterprises/devops-actions/[[doaLookup]]/index.tsx":
      $enterprises_devops_actions_doaLookup_index,
    "./routes/enterprises/handlers/[[handlerLookup]]/index.tsx":
      $enterprises_handlers_handlerLookup_index,
    "./routes/enterprises/iot/[[iotLookup]]/dashboards/[[dashboardLookup]]/index.tsx":
      $enterprises_iot_iotLookup_dashboards_dashboardLookup_index,
    "./routes/enterprises/iot/[[iotLookup]]/devices/[[deviceLookup]]/index.tsx":
      $enterprises_iot_iotLookup_devices_deviceLookup_index,
    "./routes/enterprises/iot/[[iotLookup]]/index.tsx":
      $enterprises_iot_iotLookup_index,
    "./routes/enterprises/iot/[[iotLookup]]/settings.tsx":
      $enterprises_iot_iotLookup_settings,
    "./routes/enterprises/secrets/[[secretLookup]]/index.tsx":
      $enterprises_secrets_secretLookup_index,
    "./routes/enterprises/source-connections/[[srcConnLookup]]/index.tsx":
      $enterprises_source_connections_srcConnLookup_index,
    "./routes/enterprises/sources/[[srcLookup]]/artifacts/[[artifactLookup]]/index.tsx":
      $enterprises_sources_srcLookup_artifacts_artifactLookup_index,
    "./routes/enterprises/sources/[[srcLookup]]/index.tsx":
      $enterprises_sources_srcLookup_index,
    "./routes/getting-started/applications/index.tsx":
      $getting_started_applications_index,
    "./routes/getting-started/cloud/_middleware.tsx":
      $getting_started_cloud_middleware,
    "./routes/getting-started/cloud/index.tsx": $getting_started_cloud_index,
    "./routes/getting-started/data/index.tsx": $getting_started_data_index,
    "./routes/getting-started/devices/index.tsx":
      $getting_started_devices_index,
    "./routes/index.tsx": $index,
    "./routes/teams/index.tsx": $teams_index,
  },
  islands: {
    "./islands/atoms/InteractiveMenuIcon.tsx": $atoms_InteractiveMenuIcon,
    "./islands/atoms/InteractiveSlideToggle.tsx": $atoms_InteractiveSlideToggle,
    "./islands/atoms/Redirect.tsx": $atoms_Redirect,
    "./islands/atoms/Theme.tsx": $atoms_Theme,
    "./islands/common/ProfileMenu.tsx": $common_ProfileMenu,
    "./islands/molecules/CopyInput.tsx": $molecules_CopyInput,
    "./islands/molecules/DeleteAction.tsx": $molecules_DeleteAction,
    "./islands/molecules/EaCManageIoTFormIsland.tsx":
      $molecules_EaCManageIoTFormIsland,
    "./islands/molecules/EaCManageSecretFormIsland.tsx":
      $molecules_EaCManageSecretFormIsland,
    "./islands/molecules/EaCManageSourceFormIsland.tsx":
      $molecules_EaCManageSourceFormIsland,
    "./islands/molecules/EntepriseManagementItem.tsx":
      $molecules_EntepriseManagementItem,
    "./islands/molecules/GitHubAccessAction.tsx": $molecules_GitHubAccessAction,
    "./islands/molecules/InteractiveResponsiveSet.tsx":
      $molecules_InteractiveResponsiveSet,
    "./islands/molecules/SideBar.tsx": $molecules_SideBar,
    "./islands/organisms/cloud/iot/hot-flow-input.tsx":
      $organisms_cloud_iot_hot_flow_input,
    "./islands/organisms/cloud/iot/res-group-iot-settings.tsx":
      $organisms_cloud_iot_res_group_iot_settings,
    "./islands/organisms/data/api-develop-form.tsx":
      $organisms_data_api_develop_form,
    "./islands/organisms/data/dashboard-display.tsx":
      $organisms_data_dashboard_display,
    "./islands/organisms/data/explore-form.tsx": $organisms_data_explore_form,
    "./islands/organisms/iot/device-data-flowing.tsx":
      $organisms_iot_device_data_flowing,
    "./islands/organisms/iot/devices-dashboard-controls.tsx":
      $organisms_iot_devices_dashboard_controls,
    "./islands/organisms/iot/hub-device-connection.tsx":
      $organisms_iot_hub_device_connection,
    "./islands/organisms/iot/hub-key-connection.tsx":
      $organisms_iot_hub_key_connection,
    "./islands/organisms/iot/hub-key-simulator.tsx":
      $organisms_iot_hub_key_simulator,
    "./islands/organisms/team/invite-team-member.tsx":
      $organisms_team_invite_team_member,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
