name: Docker Build and Push

on: push

env:
  IMAGE_NAME: o-biotech/biotech-manager-web:latest
  ACR_REGISTRY: ${{ env.ACR_REGISTRY }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: $IMAGE_NAME
        context: .
        file: Dockerfile
        builder: biotech-builder
        load: false

    - name: Login to Azure
      uses: azure/docker-login@v1
      with:
        login-server: $ACR_REGISTRY
        username: $ACR_USERNAME
        password: $ACR_PASSWORD

    - name: Push the Docker image to Azure Container Registry
      run: docker push $ACR_REGISTRY/$IMAGE_NAME