name: Docker Build and Push - Pre-Release

on: 
  push:
    branches: 
      - integration
      - feature/**
      - hotfix/**

env:
  IMAGE_NAME: biotech-manager-web:prerelease
  ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout the repository
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - 
        name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}
          context: .
          file: Dockerfile
          load: false
