name: Docker Build and Push

on: push

env:
  IMAGE_NAME: biotech-manager-web:latest
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create a new builder instance
      run: docker buildx create --name biotech-builder --use

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}
        context: .
        file: Dockerfile
        builder: biotech-builder
        load: false

    - name: Login to Azure
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push the Docker image to Azure Container Registry
      run: docker push ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}